production:
  adapter: postgresql
  encoding: utf8
  database: df9pga4q45hqb1
  host: ec2-52-45-73-150.compute-1.amazonaws.com
  username: iggjmzcvgmjhwl
  password: 016508eb54de9bf7050eef7986682f6dd8b34cee84aa31bd853f784bf1be0bc9
  pool: 25
  port: 5432

development:
  adapter: postgresql
  encoding: utf8
  database: df9pga4q45hqb1
  host: ec2-52-45-73-150.compute-1.amazonaws.com
  username: iggjmzcvgmjhwl
  password: 016508eb54de9bf7050eef7986682f6dd8b34cee84aa31bd853f784bf1be0bc9
  pool: 25
  port: 5432